# Uncomment the next line to define a global platform for your project
platform :ios, '14.4'

target '439FinalProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 439FinalProject
  pod 'Mapbox-iOS-SDK', '~> 6.3.0'
  pod 'SwiftOverpass'

end
